# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 13.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-3
    ports:
      - 80:8000
    links:
      - db
      - php
    volumes: &appvolumes
      - appdata:/var/www/html
      - ./../app:/var/www/html/app:delegated
      - ./../.idea/misc.xml:/var/www/html/.idea/misc.xml:delegated
      - ./../app/etc/env.php:/var/www/html/etc/env.php
      - ~/.composer:/var/www/html/var/composer_home:delegated
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock

  php:
    image: markoshust/magento-php:7.1-fpm-2
    links:
      - db
    volumes: *appvolumes

  cron:
    image: markoshust/magento-php:7.1-fpm-2
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - db
    volumes: *appvolumes

  db:
    image: mysql:5.7
    ports:
      - 3306:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    links:
#      - db
#    env_file: env/db.env
#    ports:
#      - 8080:8080
#    container_name: phpmyadmin
#    volumes:
#      - ./env/config.pma.inc.php:/etc/phpmyadmin/config.user.inc.php
#      - /sessions

volumes:
  appdata:
  dbdata:
  sockdata:


# docker-compose run --user=root --no-deps --rm -v $PWD/../../magento2-markoshust/.:/source php cp -r /source/. /var/www/html
# docker-compose up -d; docker-compose ps;
# docker-compose exec --user=root php chown -R app:app /var/www
# docker-compose exec --user=root php find var vendor pub/static pub/media app/etc -type f -exec chmod u+w `{`} `;
# docker-compose exec php chmod u+x bin/magento
# docker-compose exec php /usr/local/bin/php ./bin/magento setup:install `
#    --db-host=db `
#    --db-name=magento `
#    --db-user=magento `
#    --db-password=magento `
#    --base-url=http://magento2.localhost/ `
#    --admin-firstname=Admin `
#    --admin-lastname=User `
#    --admin-email=lucian.toza@gmail.com `
#    --admin-user=admin `
#    --admin-password=magento2 `
#    --language=en_US `
#    --currency=USD `
#    --timezone=Europe/Bucharest `
#    --use-rewrites=1
# docker-compose exec php ./bin/magento deploy:mode:set developer
# docker-compose exec php ./bin/magento indexer:reindex
# docker-compose exec php ./bin/magento cache:enable
# [SUCCESS]: Magento Admin URI: /admin_3lrd9b