# Mark Shust's Docker Configuration for Magento (https://github.com/markoshust/docker-magento)
# Version 13.0.0

version: "3"

services:
  app:
    image: markoshust/magento-nginx:1.13-3
    ports:
      - 8080:8000
    links:
      - m2db
      - php
    volumes: &appvolumes
      - appdata:/var/www/html
      - ./../app:/var/www/html/app:delegated
      - ./../.idea/misc.xml:/var/www/html/.idea/misc.xml:delegated
      - ./../app/etc/env.php:/var/www/html/etc/env.php:delegated
      - ./../app/bootstrap.php:/var/www/html/bootstrap.php:delegated
      - ./../pub/errors/local.xml:/var/www/html/pub/errors/local.xml:delegated
      - ./../docker/env/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./../docker/env/docker-php-cgi.ini:/usr/local/etc/php/conf.d/docker-php-cgi.ini
      - ~/.composer:/var/www/html/var/composer_home:delegated
      - ~/.composer:/var/www/.composer:delegated
      - sockdata:/sock

  php:
    image: markoshust/magento-php:7.1-fpm-2
    links:
      - m2db
    volumes: *appvolumes

  cron:
    image: markoshust/magento-php:7.1-fpm-2
    user: root
    command: /usr/local/bin/cronstart
    tty: true
    links:
      - m2db
    volumes: *appvolumes

  m2db:
    image: mysql:5.7
    ports:
      - 3307:3306
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin
  #  container_name: phpmyadmin
  #  links:
  #    - db
  #  restart: always
  #  ports:
  #   - 8080:80
  #  env_file: env/db.env

volumes:
  appdata:
  dbdata:
  sockdata:


# docker-compose run --user=root --no-deps --rm -v $PWD/../../magento2-markoshust/.:/source php cp -r /source/. /var/www/html
# docker-compose up -d; docker-compose ps;
# docker-compose exec --user=root php chown -R app:app /var/www
# docker-compose exec --user=root php find var vendor pub/static pub/media app/etc -type f -exec chmod u+w {} \;
# docker-compose exec php chmod u+x bin/magento
#docker-compose exec php /usr/local/bin/php ./bin/magento setup:install `
#  --db-host=m2db:3307 --db-name=magento --db-user=magento --db-password=magento `
#  --base-url=http://magento2.localhost:8080/ `
#  --admin-firstname=Admin --admin-lastname=User --admin-email=ltoza@optaros.com `
#  --admin-user=optaros --admin-password=Optaros1234! `
#  --language=en_US --currency=USD --timezone=Europe/Bucharest --use-rewrites=1
# docker-compose exec php ./bin/magento deploy:mode:set developer
# docker-compose exec php ./bin/magento indexer:reindex
# docker-compose exec php ./bin/magento cache:enable
# [SUCCESS]: Magento Admin URI: /admin

# docker-compose -f docker/docker-compose.yml exec php php bin/magento cache:flush; docker-compose -f docker/docker-compose.yml exec php rm -rf generated/metadata/* generated/code/* pub/static/adminhtml/* pub/static/frontend/* pub/static/deployed_version.txt
