<?php
/**
 * Created by PhpStorm.
 * User: lucian.toza
 * Date: 06/07/2018
 * Time: 15:24
 */

namespace Mastering\HelloWorld\Block;


use Magento\Framework\View\Element\Template;

class Main extends Template
{
    protected function _prepareLayout()
    {
//        return parent::_prepareLayout(); // TODO: Change the autogenerated stub
    }
}